id: PAE6EA76F
initial_creation_type: input
source_metadata:
  title: Pema Tekchok Loden Series
  language: bo
  description: 'Texts by and about Pema Tekchok Loden (padma theg mchog blo ldan,
    1879–1955) alias Khenpo Lhagyal (mkhan po lha rgyal) or Abu Lhagang (a bu lha
    sgang):'
  volume:
    2a32060c7c774da0a4ba66b9cfdc2de1:
      title: Biography of Dzogchen Khenchen Abu Lhagang
      parent: Biographies
created_at: '2022-03-01T01:17:38.054674'
last_modified_at: '2022-03-01T01:17:38.054677'
